services:
    laravel:
        image: laravel
        build:
            context: .
            target: development
        container_name: admin-site
        volumes:
            - ./:/var/www/html
            - ../storage/hydrogen:/var/www/html/public/hydrogen
        ports:
            - "2303:80"
        networks:
            - cliff-network

networks:
    cliff-network:
        external: true
        name: cliff-network
