services:
    laravel:
        image: admin_laravel
        build:
            context: .
            target: development
        container_name: website
        volumes:
            - ./:/var/www/html
        ports:
            - "2303:80"
        environment:
            - DB_HOST=cliff_database
            - DB_PORT=3306
            - DB_DATABASE=cliff-database
            - DB_USERNAME=root
            - DB_PASSWORD=root
        networks:
            - cliff-network

networks:
    cliff-network:
        external: true
        name: cliff-network
