services:
    laravel:
        image: laravel
        build:
            context: .
            target: development
        container_name: website
        volumes:
            - ./:/var/www/html
        ports:
            - "2303:80"
        networks:
            - cliff-network

networks:
    cliff-network:
        external: true
        name: cliff-network
