services:
  database:
    image: mysql:8.0
    container_name: db
    ports:
      - "2608:3306"
    environment:
      MYSQL_DATABASE: cliff-database
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - cliff-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "1051:6379"
    networks:
      - cliff-network

volumes:
  mysql-data:

networks:
  cliff-network:
    external: true
    name: cliff-network
